spring.application.name=CivicConnect

# DATABASE
spring.datasource.url=jdbc:postgresql://switchback.proxy.rlwy.net:37573/railway
spring.datasource.username=postgres
spring.datasource.password=WCiCaRdArVnuWzElTEotVxHZoVqrTJQY

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SERVER
server.port=${PORT:8080}

# TIMEZONE
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
